# Exploratory data analysis

## 1. Import libraries

In [1]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.figure_factory as ff

## 2. Load metadata

In [2]:
df_all = pd.read_csv("metadata.csv")
display(df_all)
df = pd.read_csv("fragments_metadata.csv")
display(df)
df_patients = pd.read_csv("ICBHI/ICBHI_Challenge_demographic_information.txt", sep="\t", header=None, names=["patient_id", "age", "sex", "BMI", "weight", "height"])
df_patients

,id,patient_id,record_id,position,acquisition,equipment,json_path,wav_path,duration
0,1,101,1b1,Al,sc,Meditron,101_1b1_Al_sc_Meditron.json,101_1b1_Al_sc_Meditron.wav,20.000
1,2,101,1b1,Pr,sc,Meditron,101_1b1_Pr_sc_Meditron.json,101_1b1_Pr_sc_Meditron.wav,20.000
2,3,102,1b1,Ar,sc,Meditron,102_1b1_Ar_sc_Meditron.json,102_1b1_Ar_sc_Meditron.wav,20.000
3,4,103,2b2,Ar,mc,LittC2SE,103_2b2_Ar_mc_LittC2SE.json,103_2b2_Ar_mc_LittC2SE.wav,20.000
4,5,104,1b1,Al,sc,Litt3200,104_1b1_Al_sc_Litt3200.json,104_1b1_Al_sc_Litt3200.wav,15.856
...,...,...,...,...,...,...,...,...,...
915,916,224,1b2,Al,sc,Meditron,224_1b2_Al_sc_Meditron.json,224_1b2_Al_sc_Meditron.wav,20.000
916,917,225,1b1,Pl,sc,Meditron,225_1b1_Pl_sc_Meditron.json,225_1b1_Pl_sc_Meditron.wav,20.000
917,918,226,1b1,Al,sc,Meditron,226_1b1_Al_sc_Meditron.json,226_1b1_Al_sc_Meditron.wav,20.000
918,919,226,1b1,Ll,sc,Meditron,226_1b1_Ll_sc_Meditron.json,226_1b1_Ll_sc_Meditron.wav,20.000
919,920,226,1b1,Pl,sc,LittC2SE,226_1b1_Pl_sc_LittC2SE.json,226_1b1_Pl_sc_LittC2SE.wav,20.000

        id  patient_id  id_record  segment  Crackle  Wheeze  duration
0        1         101          1        0        0       0   0.54325
1        2         101          1        1        0       0   1.87125
2        3         101          1        2        0       0   1.44325
3        4         101          1        3        0       0   1.90025
4        5         101          1        4        0       0   1.72825
...    ...         ...        ...      ...      ...     ...       ...
6893  6894         226        920        6        1       0   1.97225
6894  6895         226        920        7        0       0   1.84325
6895  6896         226        920        8        0       0   1.95725
6896  6897         226        920        9        1       0   1.94325
6897  6898         226        920       10        0       0   0.54325

[6898 rows x 7 columns]

     patient_id    age  sex    BMI  weight  height
0           101   3.00    F    NaN    19.0    99.0
1           102   0.75    F    NaN     9.8    73.0
2           103  70.00    F  33.00     NaN     NaN
3           104  70.00    F  28.47     NaN     NaN
4           105   7.00    F    NaN    32.0   135.0
..          ...    ...  ...    ...     ...     ...
121         222  60.00    M    NaN     NaN     NaN
122         223    NaN  NaN    NaN     NaN     NaN
123         224  10.00    F    NaN    32.3   143.0
124         225   0.83    M    NaN     7.8    74.0
125         226   4.00    M    NaN    16.7   103.0

[126 rows x 6 columns]

## 3. EDA

### 3.1. Dataset analysis

In [3]:
n_records = len(df_all)
n_segments = len(df)
n_patients = len(df["patient_id"].unique())

tot = sum(df_all["duration"])
mins_t, s_t = int(tot//60), round(tot%60, 2)
h_t, mins_t = mins_t//60, mins_t%60

dur = sum(df["duration"])
mins, s = int(dur//60), round(dur%60, 2)
h, mins = mins//60, mins%60

print(f"Number of records: {n_records}")
print(f"Number of segments: {n_segments}")
print(f"Number of patients: {n_patients}")
print(f"Total recorded time: {h_t} h {mins_t} min {s_t} s")
print(f"Corpus duration: {h} h {mins} min {s} s ({dur/tot*100:.2f}%)")

Number of records: 920
Number of segments: 6898
Number of patients: 126
Total recorded time: 5 h 29 min 33.03 s
Corpus duration: 5 h 10 min 29.91 s (94.22%)

### 3.2. Filter by age

In [4]:
df_all_merge = df_all.merge(df_patients[["patient_id", "age"]], on="patient_id", how="left")
df_all_filtered = df_all_merge[df_all_merge["age"] <= 21].reset_index(drop=True)
df_all_filtered

,id,patient_id,record_id,position,acquisition,equipment,json_path,wav_path,duration,age
0,1,101,1b1,Al,sc,Meditron,101_1b1_Al_sc_Meditron.json,101_1b1_Al_sc_Meditron.wav,20.0,3.00
1,2,101,1b1,Pr,sc,Meditron,101_1b1_Pr_sc_Meditron.json,101_1b1_Pr_sc_Meditron.wav,20.0,3.00
2,3,102,1b1,Ar,sc,Meditron,102_1b1_Ar_sc_Meditron.json,102_1b1_Ar_sc_Meditron.wav,20.0,0.75
3,11,105,1b1,Tc,sc,Meditron,105_1b1_Tc_sc_Meditron.json,105_1b1_Tc_sc_Meditron.wav,20.0,7.00
4,42,108,1b1,Al,sc,Meditron,108_1b1_Al_sc_Meditron.json,108_1b1_Al_sc_Meditron.wav,20.0,3.00
...,...,...,...,...,...,...,...,...,...,...
73,916,224,1b2,Al,sc,Meditron,224_1b2_Al_sc_Meditron.json,224_1b2_Al_sc_Meditron.wav,20.0,10.00
74,917,225,1b1,Pl,sc,Meditron,225_1b1_Pl_sc_Meditron.json,225_1b1_Pl_sc_Meditron.wav,20.0,0.83
75,918,226,1b1,Al,sc,Meditron,226_1b1_Al_sc_Meditron.json,226_1b1_Al_sc_Meditron.wav,20.0,4.00
76,919,226,1b1,Ll,sc,Meditron,226_1b1_Ll_sc_Meditron.json,226_1b1_Ll_sc_Meditron.wav,20.0,4.00
77,920,226,1b1,Pl,sc,LittC2SE,226_1b1_Pl_sc_LittC2SE.json,226_1b1_Pl_sc_LittC2SE.wav,20.0,4.00

In [5]:
df_merge = df.merge(df_patients[["patient_id", "age"]], on="patient_id", how="left")
df_filtered = df_merge[df_merge["age"] <= 21].reset_index(drop=True)
df_filtered

       id  patient_id  id_record  segment  Crackle  Wheeze  duration  age
0       1         101          1        0        0       0   0.54325  3.0
1       2         101          1        1        0       0   1.87125  3.0
2       3         101          1        2        0       0   1.44325  3.0
3       4         101          1        3        0       0   1.90025  3.0
4       5         101          1        4        0       0   1.72825  3.0
..    ...         ...        ...      ...      ...     ...       ...  ...
796  6894         226        920        6        1       0   1.97225  4.0
797  6895         226        920        7        0       0   1.84325  4.0
798  6896         226        920        8        0       0   1.95725  4.0
799  6897         226        920        9        1       0   1.94325  4.0
800  6898         226        920       10        0       0   0.54325  4.0

[801 rows x 8 columns]

#### 3.2.1. Dataset analysis after filter

In [6]:
n_records_filtered = len(df_all_filtered)
n_segments_filtered = len(df_filtered)
n_patients_filtered = len(df_filtered["patient_id"].unique())

tot_filtered = sum(df_all_filtered["duration"])
mins_t, s_t = int(tot_filtered//60), round(tot_filtered%60, 2)
h_t, mins_t = mins_t//60, mins_t%60

dur_filtered = sum(df_filtered["duration"])
mins, s = int(dur_filtered//60), round(dur_filtered%60, 2)
h, mins = mins//60, mins%60

print(f"Number of records: {n_records_filtered} ({n_records_filtered/n_records*100:.2f}%)")
print(f"Number of segments: {n_segments_filtered} ({n_segments_filtered/n_segments*100:.2f}%)")
print(f"Number of patients: {n_patients_filtered} ({n_patients_filtered/n_patients*100:.2f}%)")
print(f"Total recorded time: {h_t} h {mins_t} min {s_t} s ({tot_filtered/tot*100:.2f}%)")
print(f"Corpus duration: {h} h {mins} min {s} s ({dur_filtered/dur*100:.2f}%)")

Number of records: 78 (8.48%)
Number of segments: 801 (11.61%)
Number of patients: 51 (40.48%)
Total recorded time: 0 h 25 min 59.19 s (7.89%)
Corpus duration: 0 h 25 min 32.1 s (8.22%)

### 3.3. Age distribution

In [7]:
# --- 1. Datos ---
ages = df_patients["age"].dropna()
ages_filtered = ages[ages <=21]

# --- 3. Crear figura: 2 filas, eje X compartido ---
fig = make_subplots(
    rows=3, cols=1,
    shared_xaxes=True,
    row_heights=[0.75, 0.25, 0.25],   # histograma más grande, boxplot como "resumen" fino
    vertical_spacing=0.03,
)

# --- Histograma (normalizado a densidad para que la escala coincida con la KDE) ---
fig.add_trace(
    go.Histogram(
        x=ages,
        name="Duration",
        marker_color="steelblue",
        opacity=0.75,
        showlegend=False,
    ),
    row=1, col=1
)
fig.add_trace(
    go.Histogram(
        x=ages_filtered,
        name="Duration",
        marker_color="forestgreen",
        opacity=0.75,
        showlegend=False,
    ),
    row=1, col=1
)

# --- Boxplot horizontal ---
fig.add_trace(
    go.Box(
        x=ages,
        name="Age",
        marker_color="steelblue",
        line_color="steelblue",
        boxpoints="outliers",   # muestra outliers como puntos
        showlegend=False,
        boxmean="sd"
    ),
    row=2, col=1
)

# --- Boxplot horizontal ---
fig.add_trace(
    go.Box(
        x=ages_filtered,
        name="Age (≤ 21 y/o)",
        marker_color="forestgreen",
        line_color="forestgreen",
        boxpoints="outliers",   # muestra outliers como puntos
        showlegend=False,
        boxmean="sd"
    ),
    row=3, col=1
)

# --- 4. Layout ---
fig.update_layout(
    template="plotly_white",
    title_text="Age patient distribution",
    font=dict(size=15),
    title_font=dict(size=20),
    bargap=0.02,
    barmode="overlay"
)
fig.update_yaxes(title_text="Count", row=1, col=1)
fig.update_yaxes(showticklabels=True, row=3, col=1)
fig.update_xaxes(title_text="Age (years)", row=3, col=1)

fig.show()
fig.write_image("assets/age_patient_distribution.png", scale=5)

### 3.4. Duration distribution

In [8]:
# --- 1. Datos ---
durations = df["duration"].dropna()
durations_filtered = df_filtered["duration"].dropna()


# --- 3. Crear figura: 2 filas, eje X compartido ---
fig = make_subplots(
    rows=3, cols=1,
    shared_xaxes=True,
    row_heights=[0.75, 0.25, 0.25],   # histograma más grande, boxplot como "resumen" fino
    vertical_spacing=0.03,
)

# --- Histograma (normalizado a densidad para que la escala coincida con la KDE) ---
fig.add_trace(
    go.Histogram(
        x=durations,
        name="Duration",
        marker_color="chocolate",
        opacity=0.75,
        showlegend=False,
    ),
    row=1, col=1
)

fig.add_trace(
    go.Histogram(
        x=durations_filtered,
        name="Duration",
        marker_color="forestgreen",
        opacity=0.75,
        showlegend=False,
    ),
    row=1, col=1
)

# --- Boxplot horizontal ---
fig.add_trace(
    go.Box(
        x=durations,
        name="Duration",
        marker_color="chocolate",
        line_color="chocolate",
        boxpoints="outliers",   # muestra outliers como puntos
        showlegend=False,
        boxmean="sd"
    ),
    row=2, col=1
)

fig.add_trace(
    go.Box(
        x=durations_filtered,
        name="Duration",
        marker_color="forestgreen",
        line_color="forestgreen",
        boxpoints="outliers",   # muestra outliers como puntos
        showlegend=False,
        boxmean="sd"
    ),
    row=3, col=1
)

# --- 4. Layout ---
fig.update_layout(
    template="plotly_white",
    title_text="Duration distribution",
    font=dict(size=15),
    title_font=dict(size=20),
    bargap=0.02,
    barmode="overlay",
)
fig.update_yaxes(title_text="Count", row=1, col=1)
fig.update_yaxes(showticklabels=False, row=2, col=1)
fig.update_xaxes(title_text="Duration (s)", row=2, col=1)

fig.show()
fig.write_image("assets/duration_distribution.png", scale=5)

### 3.5. Label distribution

In [9]:
matrix = pd.crosstab(df['Wheeze'], df['Crackle'])
matrix = matrix.reindex(index=[0, 1], columns=[0, 1], fill_value=0)

z = matrix.values
total = z.sum()

# Texto personalizado: count + porcentaje
annotations_text = [
    [f'{z[i][j]}<br>({z[i][j]/total*100:.1f}%)' for j in range(z.shape[1])]
    for i in range(z.shape[0])
]

x_labels = ['0', '1']
y_labels = ['0', '1']

fig = ff.create_annotated_heatmap(
    z=z,
    x=x_labels,
    y=y_labels,
    annotation_text=annotations_text,
    colorscale='BuPu',
    showscale=True
)

fig.update_layout(
    title=dict(
        text='Contingence matrix: Wheeze vs Crackle',
        y=0.98,          # posición vertical del título (más cerca del borde superior)
        x=0.5,
        xanchor='center'
    ),
    xaxis_title='Crackle',
    yaxis_title='Wheeze',
    margin=dict(t=100),  # aumenta el espacio superior total (por defecto suele ser ~60-80)
    width=500,
    height=500,
    font=dict(size=14)
)
fig.update_yaxes(autorange="reversed")  # opcional, orden clásico de matriz

fig.show()
fig.write_image("assets/label_distribution.png", scale=5)

### 3.5.1. Filtered

In [ ]:
matrix = pd.crosstab(df_filtered['Wheeze'], df_filtered['Crackle'])
matrix = matrix.reindex(index=[0, 1], columns=[0, 1], fill_value=0)

z = matrix.values
total = z.sum()

# Texto personalizado: count + porcentaje
annotations_text = [
    [f'{z[i][j]}<br>({z[i][j]/total*100:.1f}%)' for j in range(z.shape[1])]
    for i in range(z.shape[0])
]

x_labels = ['0', '1']
y_labels = ['0', '1']

fig = ff.create_annotated_heatmap(
    z=z,
    x=x_labels,
    y=y_labels,
    annotation_text=annotations_text,
    colorscale='BuPu',
    showscale=True
)

fig.update_layout(
    title=dict(
        text='Contingence matrix: Wheeze vs Crackle',
        y=0.98,          # posición vertical del título (más cerca del borde superior)
        x=0.5,
        xanchor='center'
    ),
    xaxis_title='Crackle',
    yaxis_title='Wheeze',
    margin=dict(t=100),  # aumenta el espacio superior total (por defecto suele ser ~60-80)
    width=500,
    height=500,
    font=dict(size=14)
)
fig.update_yaxes(autorange="reversed")  # opcional, orden clásico de matriz

fig.show()
fig.write_image("assets/label_distribution_filtered.png", scale=5)